### PR TITLE
Fixes float formatting rounding to 6 decimals

### LINKED ISSUE #11: Float printing
When printing floats for the statistics message, it always rounds to 6 decimals, either by adding trailing 0's or rounding the number.

Fixed by replacing %f by %v in the log message formatter in msgStatistics.

### PR DESCRIPTION
**Pull request by chrisvdg**
fixes #11

### CODE REVIEW

File: logger.go [hunk 1]
```diff
@@ -153,7 +153,7 @@ func msgStatistics(msg interface{}) (string, error) {
 		return "", err
 	}
 
-	str := fmt.Sprintf("%s:%f|%s",
+	str := fmt.Sprintf("%s:%v|%s",
```
Comment (GlenDC) [inline logger.go]: Fairly sure you want to do something like `%.3f` instead, if you want to limit yourself to a precision of 3. Should be faster than having to rely on the generic `%v`, and it will give you a warning in case you are giving a non-float value.

By the way, where are you getting this limit of precision 3? Was checking through https://github.com/zero-os/0-core/blob/master/docs/monitoring/stats.md, and I can't find it mentioning anywhere about a precision limit?

Comment (chrisvdg) [reply logger.go]: @GlenDC  I don't want to limit the precision, as mentioned in the issue ( #11 ), using %f limits the precision to 6 decimals, as I want to leave the precision up to whoever is using it, switching %f to %v will set the precision to the whatever the value's precision is

Comment (GlenDC) [reply logger.go]: In that case I think you can use `%g` in that case, I'm fairly sure that's what `%v` uses for floats  in such case. More info: https://godoc.org/fmt

Comment (chrisvdg) [reply logger.go]: seems to work, pushed the change to `%g`

File: logger.go [hunk 2]
```diff
@@ -153,7 +153,7 @@ func msgStatistics(msg interface{}) (string, error) {
 		return "", err
 	}
 
-	str := fmt.Sprintf("%s:%f|%s",
+	str := fmt.Sprintf("%s:%g|%s",
```
Comment (GlenDC) [inline logger.go]: I think you want it to be `%-1g` thinking about it:

https://play.golang.org/p/La3z6G47_T

Comment (chrisvdg) [reply logger.go]: what does that do? playing with `%g` or `%-1g` in that example doesn't seem to make a difference?

Comment (GlenDC) [reply logger.go]: it will print `0.23400` as `0.234`, instead of `0.23400`

Comment (GlenDC) [reply logger.go]: Either way, after some poking around and debugging some playground with [`delve`](https://github.com/derekparker/delve), I'm pretty sure that `%v` will do the same thing as `%-1g` for a float32/float64 value. So we can just as well explicitly define it ourselves, to be clear in what we want. If that's indeed the behavior we want.

And reading from your comment, that is what you want:

you can see that `-1` will trigger the code which is commented as:

> `// Negative precision means "only as much as needed to be exact."`

And for `%g/%G` that means cutting of trailing `0`s, AFAIK.

Source: https://github.com/golang/go/blob/master/src/strconv/ftoa.go#L107-L127
